### ISSUE TITLE
Can't create new note 

### ISSUE THREAD

**Issue by OrhanOzkercin** [onuriltan/note-manager#79]
While trying to create new note, spinner always spinning but nothing happens.

<img src="https://i.ibb.co/HNdx00f/ss.gif">

**Comment by onuriltan** [comment]
Is this happen on local or in [production](notemanagerapp.herokuapp.com) ?

**Comment by OrhanOzkercin** [comment]
It happened in production, I sign in with Facebook and tried to create note. 
I tried on this link: https://notemanagerapp.herokuapp.com/

**Comment by onuriltan** [comment]
The problem was facebook was not returning user's email from the `passport facebook-login strategy`. To fix that I added #80 ` profileFields: ['id', 'emails', 'name']` to tell passport to return facebook user's id, email and name. Could you try again?

**Comment by OrhanOzkercin** [comment]
Now spinner is okey but still can not save any note. 

![gif](https://i.ibb.co/Z644mCQ/ss.gif)

**Comment by onuriltan** [comment]
@OrhanOzkercin Your user had not email while I was saving, I've put the extra check so it should be fixed now, thanks for raising the issue 🙏

**Comment by OrhanOzkercin** [comment]
Yes, now everything is fine. This is a nice app, congratulations (:
